spring:
  mail:
    username: sk41442457@gmail.com
    password: syqx aydv jzrz hupe

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "413352049744-nc0i6r0go3e8bqthlinsvqnbou98emdm.apps.googleusercontent.com"
            client-secret: "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"
            scope:
              - email
              - profile

jwt:
  secret-key: "7kQ43HmV4oMHcZgyNfsxbVoYDSdN9WBvJCn8KKM3k5v"
  expiration: 3600000

alan:
  client-id: "e5aef478-60cf-4a46-adc3-06a52562affd"
  base-url: "https://kdt-api-function.azurewebsites.net/api/v1"


iamport:
  api:
    key: "6750434272406525"
    secret: "OLGmcbnxSq9w0j8exurIuYiLdMHsBTl0b58F49Shm1kYIOzQw1VOBz3k2ovgIKjV8PQ7U7SCPDoYDi2V"