spring:
  mail:
    username: sk41442457@gmail.com
    password: syqx aydv jzrz hupe

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "413352049744-nc0i6r0go3e8bqthlinsvqnbou98emdm.apps.googleusercontent.com"
            client-secret: "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"
            scope:
              - email
              - profile

jwt:
  secret-key: "7kQ43HmV4oMHcZgyNfsxbVoYDSdN9WBvJCn8KKM3k5v"
  expiration: 3600000

alan:
  client-id: "e5aef478-60cf-4a46-adc3-06a52562affd"
  base-url: "https://kdt-api-function.azurewebsites.net/api/v1"


iamport:
  api:
    key: "6750434272406525"
    secret: "S5th3I9aS98NTUf9MSiJwpStaH0i2XGId7I5BvpbMI8zkigz9IIymavLVIg1gtVCD7vwlc6i6FaY3I9B"

portone:
  api:
    secret: "q41oAttb9Ku7uXb5FqoFbgD32kORmOgpPK2nwLR0PILB93NkgTN3GHRn1TxLtHxEvk99ZGkijWVNc60f"
    store-id: "store-96652963-c75c-41dc-bb4c-716d3261cae8"
    kakao-channel-key: "channel-key-741341c6-3a10-48be-b183-e5be2bb40694"